on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          depricated=true
          if [[deprecated]]; then
            echo "::warning::Deprecated function found"
          fi
