name: First Workfolw

on:
  push: 
    branches: 
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "welcome to our first GitHub Actions Workflow!"

      - name: Checkout repository
        uses: actions/checkout@v6.1.0

      - name: List repository file
        run: ls -la
        
